// Objective-C API for talking to github.com/consensus-ai/sentient-network/mobile Go package.
//   gobind -lang=objc -prefix="MS" github.com/consensus-ai/sentient-network/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __MSMobile_H__
#define __MSMobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MSMobileWallet;

@interface MSMobileWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)addressAtIndex:(long)index;
- (NSString*)getBalance;
- (BOOL)isUnlocked;
- (BOOL)lock;
- (NSString*)makeNewAddress;
- (long)numAddresses;
- (NSString*)primarySeed;
/**
 * returns TransactionID
 */
- (NSString*)sendSen:(NSString*)dest amount:(NSString*)amount;
- (BOOL)setupClient:(NSString*)baseUrl;
- (BOOL)unlock:(NSString*)password;
@end

FOUNDATION_EXPORT MSMobileWallet* MSMobileCreateNewWallet(NSString* path, NSString* password);

FOUNDATION_EXPORT MSMobileWallet* MSMobileCreateWalletWithSeed(NSString* path, NSString* password, NSString* seedStr);

/**
 * For any API call, if you get a nil/false/0/"", check lastError for an error message
 */
FOUNDATION_EXPORT NSString* MSMobileLastError(void);

FOUNDATION_EXPORT MSMobileWallet* MSMobileOpenWallet(NSString* path, NSString* password);

#endif
