
// Objective-C API for talking to the following Go packages
//
//	github.com/consensus-ai/sentient-network/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MSMobile_FRAMEWORK_H__
#define __MSMobile_FRAMEWORK_H__

#include "MSMobile.objc.h"
#include "Universe.objc.h"

#endif
