// Objective-C API for talking to github.com/consensus-ai/sentient-network/mobile Go package.
//   gobind -lang=objc -prefix="MS" github.com/consensus-ai/sentient-network/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __MSMobile_H__
#define __MSMobile_H__

@import Foundation;
#include "Universe.objc.h"


@class MSMobileTransaction;
@class MSMobileWallet;

/**
 * this represents a "user's view" of a transaction; that is, it
only includes information pertinent to their wallet. so, a flag
indicating incoming/outgoing and a list of "other addresses"
(either sender or recipient depending on the flag) is
sufficient.

json included since serialized from client this structure
 */
@interface MSMobileTransaction : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)identifier;
- (void)setIdentifier:(NSString*)v;
- (BOOL)incoming;
- (void)setIncoming:(BOOL)v;
// skipped field Transaction.Addresses with unsupported type: []string

- (NSString*)amount;
- (void)setAmount:(NSString*)v;
- (long)stamp;
- (void)setStamp:(long)v;
- (BOOL)matured;
- (void)setMatured:(BOOL)v;
- (NSString*)singleAddress;
@end

@interface MSMobileWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)addressAtIndex:(long)index;
- (NSString*)estimatedFee;
- (NSString*)getBalance;
- (long)getNumTransactions;
- (BOOL)isUnlocked;
- (BOOL)lock;
- (NSString*)makeNewAddress;
- (long)numAddresses;
- (NSString*)primarySeed;
/**
 * returns TransactionID
 */
- (NSString*)sendSen:(NSString*)dest amount:(NSString*)amount;
- (BOOL)setupClient:(NSString*)baseUrl;
- (MSMobileTransaction*)transactionAtIndex:(long)index;
- (BOOL)unlock:(NSString*)password;
@end

FOUNDATION_EXPORT MSMobileWallet* MSMobileCreateNewWallet(NSString* path, NSString* password);

FOUNDATION_EXPORT MSMobileWallet* MSMobileCreateWalletWithSeed(NSString* path, NSString* password, NSString* seedStr);

/**
 * For any API call, if you get a nil/false/0/"", check lastError for an error message
 */
FOUNDATION_EXPORT NSString* MSMobileLastError(void);

FOUNDATION_EXPORT MSMobileWallet* MSMobileOpenWallet(NSString* path, NSString* password);

#endif
